### PR TITLE
Add Acknowledgments section

### PR DESCRIPTION
**Pull request by mounirlamouri**
I've added folks that made PR or left comments/opened issues that led to PRs. Some folks didn't put their real names so I didn't add them.

@beaufortfrancois did I miss anyone?

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/85.html" title="Last updated on Sep 24, 2018, 6:34 PM GMT (b26aa8f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/85/586ce7e...b26aa8f.html" title="Last updated on Sep 24, 2018, 6:34 PM GMT (b26aa8f)">Diff</a>

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
@ewoerner Do yo want to share your name so that we can add you to the Acknowledgments section?

**Comment by beaufortfrancois** [comment]
@jeremysjones Do yo want to share your name so that we can add you to the Acknowledgments section?

**Comment by ewoerner** [comment]
@beaufortfrancois profile updated.

**Comment by beaufortfrancois** [comment]
Thanks @ewoerner!

**Comment by jeremysjones** [comment]
Jeremy Jones

**Comment by beaufortfrancois** [comment]
Thanks @jeremysjones!

**Pull request merged**
