### PR TITLE
Add initial spec based on explainer

### PR DESCRIPTION
**Pull request by beaufortfrancois**
@mounirlamouri As promised, here it is.

FYI, bikeshed is not happy:

```
LINK ERROR: No 'dfn' refs found for 'htmlvideoelement'.
<a data-link-type="dfn" data-lt="HTMLVideoElement"><code>HTMLVideoElement</code></a>
LINK ERROR: No 'dfn' refs found for 'remote playback specification'.
<a data-link-type="dfn" data-lt="Remote Playback specification">Remote Playback specification</a>
LINK ERROR: No 'dfn' refs found for 'feature policy specification'.
<a data-link-type="dfn" data-lt="Feature Policy specification">Feature Policy specification</a>
```

### CODE REVIEW

**Comment by mounirlamouri** [comment]
Maybe it shouldn't be a literal copy-paste of the explainer :)

The errors you see are because bikeshed tries to linkify thinks that are inside anchor tags like `<a>foo</a>`. It links to whatever is defined as `foo` with `<dfn>foo</a>`.

What about following a template using Media Session, Remote Playback, or Media Capabilities and fill in the blank with the Picture in Picture explainer? :)

**Comment by beaufortfrancois** [comment]
@mounirlamouri I'm still having some trouble with 🚲 but I think it is in a better shape. WDYT?

**Comment by mounirlamouri** [comment]
In general, I would recommend against using the markdown syntax in bikeshed. I find it confusing to read markdown and HTML mixed together. Though, it might be because of my previous life as spec editor working with respec.

Is there something in particular that causes you trouble and you want me to look at?

**Comment by beaufortfrancois** [comment]
I tend to use MD as much as possible as I find it much easier to read and less prone to HTML errors. I'll use HTML only when I have to (descriptions lists, IDL, etc.)

**Pull request merged**
