### PR TITLE
Add auto-deploy script using travis.

### PR DESCRIPTION
**Pull request by mounirlamouri**
@beaufortfrancois PTAL :)

### CODE REVIEW

**Comment by marcoscaceres** [comment]
fixed IPR issue ... all good now :)

**Comment by mounirlamouri** [comment]
Thanks @marcoscaceres I've also linked my GH account with W3C. Not sure why it wasn't linked already (or the link broke?).

**Comment by beaufortfrancois** [comment]
LGTM

**Comment by marcoscaceres** [comment]
Oh, I was going to r- till you fix the deploy script over in the Permissions API repo 😜

**Pull request merged**
