### PR TITLE
Treat DocumentOrShadowRoot as an interface mixin

### PR DESCRIPTION
**Pull request by foolip**
Matching https://dom.spec.whatwg.org/#mixin-documentorshadowroot.

***
<a href="https://pr-preview.s3.amazonaws.com/foolip/picture-in-picture/pull/114.html" title="Last updated on Jan 21, 2019, 2:07 PM UTC (03da806)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/114/658c859...foolip:03da806.html" title="Last updated on Jan 21, 2019, 2:07 PM UTC (03da806)">Diff</a>

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
Thanks @foolip!

Even though it is not supported in Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=781257), do you suggest I add it to the spec?
How about Web Platform Tests? Are they going to complain?

**Comment by foolip** [comment]
Partial interfaces, the old [NoInterfaceObject] + `A implements B` pattern and the new interface mixin + `A includes B` pattern and are just a spec writing convenience, doing exactly the same thing as if everything was defined in a single interface definition.

So no tests of behavior would be affected by this. idlharness.js tests already handle mixins. After the spec is updated, a PR against wpt will be automatically be created, I'll try to remember to mention you there so you can see how it works.

**Comment by beaufortfrancois** [comment]
I'll be monitoring these changes. Thanks!

FYI @mounirlamouri

**Comment by foolip** [comment]
The change reached wpt in https://github.com/web-platform-tests/wpt/pull/14990.

**Pull request merged**
